export enum AuthNavigate {
  Login = 'signin',
  Registration = 'signup',
  RefreshToken = 'refresh-token',
  NewPassword = 'new-password',
  PasswordRecovery = 'password-recovery',
  RegistrationConfirmation = 'registration-confirmation',
  RegistrationEmailResending = 'registration-email-resending',
  GetProfile = 'me',
  Logout = 'logout',
  RegistrationGoogle = 'google',
  RegistrationGoogleCallback = 'google/callback',
  RegistrationGitHub = 'github',
  RegistrationGitHubCallback = 'github/callback',
}
