export enum AuthNavigate {
  Login = 'signin',
  Registration = 'signup',
  RefreshToken = 'refresh-token',
  NewPassword = 'new-password',
  PasswordRecovery = 'password-recovery',
  RegistrationConfirmation = 'registration-confirmation',
  RegistrationEmailResending = 'registration-email-resending',
  GetProfile = 'me',
  Logout = 'logout',
  GithubLogin = 'github/login',
  GithubCallback = 'github/callback',
  GoogleLogin = 'google/login',
  GoogleRedirect = 'google/redirect',
}
